data<-read.delim("household_power_consumption.txt",sep=";")
subdata<-data[data$Date%in%c("1/2/2007","2/2/2007"),]
GlobalActivePower<-as.numeric(subdata$Global_active_power)
submetering1<-as.numeric(subdata$Sub_metering_1)
submetering2<-as.numeric(subdata$Sub_metering_2)
submetering3<-as.numeric(subdata$Sub_metering_3)
datetime<-strptime(paste(subdata$Date,subdata$Time),"%d/%m/%Y %H:%M:%S")
Voltage<-as.numeric(subdata$Voltage)
Globalreactivepower<-as.numeric(subdata$Global_reactive_power)
png("plot4.png",width=480,height=480)
par(mfrow=c(2,2))
plot(datetime,GlobalActivePower,type = "l",xlab = " ",ylab = "Glbal Active Power")
plot(datetime,Voltage,type="l")
plot(datetime,submetering1,type="l",xlab=" ",ylab="Energy sub metering")
lines(datetime,submetering2,type="l",col="red")
lines(datetime,submetering3,type="l",col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty = 1,bty = "n", col=c("black","red","blue"))
plot(datetime,Globalreactivepower,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()